// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tQN_Cpp
List tQN_Cpp(NumericVector r, NumericVector theta, NumericVector A_theta, NumericVector A_r, NumericVector B_theta, NumericVector B_r, NumericVector H_theta, NumericVector H_r);
RcppExport SEXP argyle_tQN_Cpp(SEXP rSEXP, SEXP thetaSEXP, SEXP A_thetaSEXP, SEXP A_rSEXP, SEXP B_thetaSEXP, SEXP B_rSEXP, SEXP H_thetaSEXP, SEXP H_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A_theta(A_thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A_r(A_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B_theta(B_thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B_r(B_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type H_theta(H_thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type H_r(H_rSEXP);
    __result = Rcpp::wrap(tQN_Cpp(r, theta, A_theta, A_r, B_theta, B_r, H_theta, H_r));
    return __result;
END_RCPP
}
