// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dist_ibs
NumericMatrix dist_ibs(NumericMatrix x);
RcppExport SEXP _argyle_dist_ibs(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_ibs(x));
    return rcpp_result_gen;
END_RCPP
}
// tQN_Cpp
List tQN_Cpp(NumericVector r, NumericVector theta, NumericVector A_theta, NumericVector A_r, NumericVector B_theta, NumericVector B_r, NumericVector H_theta, NumericVector H_r);
RcppExport SEXP _argyle_tQN_Cpp(SEXP rSEXP, SEXP thetaSEXP, SEXP A_thetaSEXP, SEXP A_rSEXP, SEXP B_thetaSEXP, SEXP B_rSEXP, SEXP H_thetaSEXP, SEXP H_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A_theta(A_thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A_r(A_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B_theta(B_thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B_r(B_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type H_theta(H_thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type H_r(H_rSEXP);
    rcpp_result_gen = Rcpp::wrap(tQN_Cpp(r, theta, A_theta, A_r, B_theta, B_r, H_theta, H_r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_argyle_dist_ibs", (DL_FUNC) &_argyle_dist_ibs, 1},
    {"_argyle_tQN_Cpp", (DL_FUNC) &_argyle_tQN_Cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_argyle(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
