# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tQN_Cpp <- function(r, theta, A_theta, A_r, B_theta, B_r, H_theta, H_r) {
    .Call('argyle_tQN_Cpp', PACKAGE = 'argyle', r, theta, A_theta, A_r, B_theta, B_r, H_theta, H_r)
}

